language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ph5iU1JZtNipTPhND/khg4mh7f5BI/1epd1sEBx4KKn/20eMBEzdgMVEHzK40NFB28FRX9HEE0ESaMW+QR6hwfA5nCLd1QKlaEvcqzOdE2XCr4Uw7Fh3tWt3ZUkil7RE7Kfyri03LUdoNhhsmdQUfJXDn1LHl2kmZP2ApJi/nA/jbBmQkmLSAu5+aSs0bPyrX/fbB1VDR4LYkJAenoeEuXsm+lcJ91xl6zsq/JWtE80nsRngAVL2te73gNLV05Zyu2oNVg9vB4jw1gf9WDF1tJCX9zcUJUfRKQ0HBLgTzhqXz7LNcLyGIviJrP2v4yHtsdxk0Ra0VGV5j/d3v8j7i1+9mQZ2CnqTwkVcmu3TiLc2P1/rGvdi1PbqU0ldQDLJ1a0iSLtLQPNtLEFI2E5dhc0gsHa0aHCTLnmf41A/Eky1eAVX7rHEbScjWhJECcnLdAayQi6i4+maYdLzPekyHi4vZRa89QgUY3fNaYf8XwBdax5EyEi1VFY6Gf3eZyyIvsPKponPLIQBKzTHlEjv4c3qTuLE1AaiY06hoTFmn6QEN0naE9jcc7P3KVc5jIoTFNQYyds5G+CrL6s84rqTlb0aTweEa5tGQbzpWpxH1JwVmgoQIy6XfiH4r5VM/YL1EBuc6houusB565g160iZLT9Wwhc+q6tnlnB2NgUz6E4=
  app: still-shelf-96120
  on:
    repo: rk-codes/trip-journal-app
